name: ImplementaciÃ³n automatizada development

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.16.0"

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Instalar dependencias
        run: pnpm install
        env:
          PNPM_WORKSPACE_ROOT: .

      - name: Crear archivo .env desde secrets
        run: |
          echo "VITE_APP_VERSION=${{ secrets.VITE_APP_VERSION_DEV }}">>.env
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME_DEV }}">>.env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL_DEV }}">>.env
          echo "VITE_ECHO_BROADCASTER=${{ secrets.VITE_ECHO_BROADCASTER_DEV }}" >> .env
          echo "VITE_ECHO_KEY=${{ secrets.VITE_ECHO_KEY_DEV }}">>.env
          echo "VITE_ECHO_WS_HOST=${{ secrets.VITE_ECHO_WS_HOST_DEV }}">>.env
          echo "VITE_ECHO_WS_PORT=${{ secrets.VITE_ECHO_WS_PORT_DEV }}">>.env
          echo "VITE_ECHO_WSS_PORT=${{ secrets.VITE_ECHO_WSS_PORT_DEV }}">>.env
          echo "VITE_ECHO_FORCE_TLS=${{ secrets.VITE_ECHO_FORCE_TLS_DEV }}">>.env
          echo "VITE_ECHO_DISABLE_STATS=${{ secrets.VITE_ECHO_DISABLE_STATS_DEV }}">>.env
          echo "VITE_ECHO_ENABLED_TRANSPORTS=${{ secrets.VITE_ECHO_ENABLED_TRANSPORTS_DEV }}">>.env

      - name: Compilar proyecto
        run: pnpm run build -m pwa

      - name: Verificar archivos generados
        run: ls -R dist

      - name: Subir archivos al servidor (directorio temporal)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          source: "dist"
          target: "/tmp/rifaplay-dev_temp"
          strip_components: 1
          rm: true

      - name: Mover archivos y establecer permisos en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            sudo rm -rf /var/www/rifaplay/store/*
            sudo mv /tmp/rifaplay-dev_temp/* /var/www/rifaplay/store/
            sudo find /var/www/rifaplay/market/ -type d -exec chmod 755 {} \;
            sudo find /var/www/rifaplay/market/ -type f -exec chmod 644 {} \;
            sudo chown -R www-data:www-data /var/www/rifaplay/market
            rm -rf /tmp/rifaplay-dev_temp
