name: ImplementaciÃ³n automatizada

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8           
      - name: Instalar dependencias
        run: pnpm install --force
      - name: Crear archivo .env desde secrets
        run: |
          echo "VITE_API_URL=${{secrets.VITE_API_URL_DEV}}">>.env

      - name: Compilar proyecto 
        run: pnpm run build -m pwa

      - name: Verificar archivos generados
        run: ls -R dist

      - name: Subir archivos al servidor (directorio temporal)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/tmp/rifaplay-dev_temp"
          strip_components: 1
          rm: true

      - name: Mover archivos y establecer permisos en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/rifaplay/store/*
            sudo cp -r /tmp/rifaplay-dev_temp/* /var/www/rifaplay/store
            sudo chown -R www-data:www-data /var/www/rifaplay/store
            sudo chmod -R 755 /var/www/rifaplay/store
            rm -rf /tmp/rifaplay-dev_temp
